#!/bin/bash

set -e

target_path="${1:-.}"

gfind "$target_path" -type f \( -path "*/*.kts" -o -path "*/*.kt" -not -path "*/build/*/*.kts" -not -path "*/build/*/*.kt" \) -print0 | xargs -0 ktfmt --kotlinlang-style
